
version: '3.3'
services:

  db-socle:
    image: postgres:latest
    container_name: postgres-socle
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=killbill
    volumes:
      - db_postres_socle:/var/lib/postgresql/data
    networks:
      - net-socle

# version: '3.3'
# services:

#   db-socle:
#     image: postgres:latest
#     container_name: postgres-socle
#     restart: always
#     expose:
#       - 5432
#     ports:
#       - "5432"
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: CywN&H5Z^M87
#       POSTGRES_DB: migration
#     volumes:
#       - db_postres_socle:/var/lib/postgresql/data
#     networks:
#       - net-socle