spring:
  application:
    name: microservice-subscription
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/subscription
      Primary:
        database:
          microRefConsumerEmpl
      Qualifier:
        database:
          microRefProducer
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    consumer:
      bootstrap-servers: localhost:9092
      group-id: MicroRefConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    listener:
      ack-mode: MANUAL_IMMEDIATE

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password123@localhost:8761/eureka/

killbill:
  host: http://localhost:8080
  username: admin
  password: password
  apiKey: oga
  apiSecret: oga
