version: '3'

services:
  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:22
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth
    command:
      - "start-dev"
