version: '3.3'
services:

  zookeeper:
    container_name: zookeeper-socle
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - net-socle
  kafka:
      image: wurstmeister/kafka
      depends_on:
        - zookeeper
      container_name: "kafka-socle"
      ports:
        - "9093:9092"
      expose:
        - "9093"
      environment:
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9093
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "topic_test:1:1"

      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - net-socle

# version: '3.3'
# services:

#   zookeeper:
#     image: confluentinc/cp-zookeeper:latest
#     restart: always
#     ports:
#       - 2181
#     container_name: "zookeeper-socle"
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#     networks:
#       - net-socle
#   kafka:
#     image: confluentinc/cp-kafka:latest
#     restart: always
#     ports:
#       - 9092
#     depends_on:
#       - zookeeper
#     container_name: "kafka-socle"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_LISTENERS: LISTENER_INSIDE://0.0.0.0:29092,LISTENER_HOST://0.0.0.0:9092
#       KAFKA_ADVERTISED_LISTENERS: LISTENER_INSIDE://kafka:29092,LISTENER_HOST://kafka:9092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INSIDE:PLAINTEXT,LISTENER_HOST:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INSIDE
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_HEAP_OPTS: " -Xmx256m -Xms256m"
#     networks:
#       - net-socle
