version: '3'

volumes:
  postgres_data:
      driver: local
  pgdata_keycloak:
networks:
  keycloak_dev_network:
    driver: bridge
      
services:
  keycloak:
      image: quay.io/keycloak/keycloak:19.0.3
      container_name: keycloak_image3
      environment:
        KC_DB: postgres
        KC_DB_URL_HOST: pg_db3
        KC_DB_URL_DATABASE: keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_SCHEMA: public
        KC_DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KEYCLOAK_IMPORT: /tmp/realm-export.json
      command: 
      - "start-dev"
      - "--import-realm"
      volumes:
      - ./export.json:/opt/keycloak/data/import/realm.json
      - ./keycloak-themes/keywind/theme/keywind/:/opt/keycloak/themes/keywind/
      ports:
        - 8180:8080
      networks:
      - keycloak_dev_network
  postgres_keycloak:
        image: postgres
        container_name: pg_db3
        volumes:
          - pgdata_keycloak:/var/lib/postgres/data
        environment: 
          POSTGRES_DB: keycloak
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: password
        ports:
          - "5555:5432"
        networks:
          - keycloak_dev_network

