version: '3'
services:
  keycloak:
    image: bitnami/keycloak:19.0.2
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - DB_VENDOR=postgres
      - DB_ADDR=postgres-socle
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - db-socle
    networks:
      - net-socle
